Dmitry Puzyrev K33402
Backend-ITMO-2021/Lecture-7 pull request #3
Opened 2021-05-12 09:10 UTC by dipuzyrev

2021-05-15 13:00 UTC, IlyaHalsky requested changes
Бонус не могу засчитать

2021-05-15 13:00 UTC, IlyaHalsky commented on src/main/scala/ru/ifmo/backend_2021/Parser.scala
> +    case _ if x.length > 0 && predicate(x.head) => Some(x.head, x.drop(1))
can replace with s.headOption.exists(predicate)

2021-05-15 13:00 UTC, IlyaHalsky commented on src/main/scala/ru/ifmo/backend_2021/Parser.scala
> +    case _ => alternative.empty[Unit]
Не правильно сработает на println(brackets.runParser("())("))

2021-05-15 13:51 UTC, dipuzyrev commented
Пофикшу 👌

2021-05-15 18:11 UTC, dipuzyrev commented
Done

2021-05-16 15:05 UTC, IlyaHalsky commented
55

2021-05-16 15:05 UTC, closed without merging